---
title: "WELL project"
author: "Rachel Weng"
date: "12/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(simr)

### Create covarites 
subj <- factor(1:30)      # 30 participants
train <- c("mod","inst")    # training condition
verb <- c("verb1", "verb2", "verb3", "verb4")
testorder <- 1:4      # baseline + test1 + test2 + test3

subj_full <- rep(subj, 16)
train_full <- rep(rep(train, each=1), 240)
verb_full <- rep(rep(verb, each=30), 4)
testorder_full <- rep(rep(testorder, each=120), 1)
list1 <- data.frame(subject=subj_full, verb=factor(verb_full), traincond=factor(train_full), testorder=factor(testorder_full))

subj <- factor(1:30)
train <- c("inst","mod")
verb <- c("verb5", "verb6", "verb7", "verb8")
testorder <- 1:4

subj_full <- rep(subj, 16)
train_full <- rep(rep(train, each=1), 240)
verb_full <- rep(rep(verb, each=30), 4)
testorder_full <- rep(rep(testorder, each=120), 1)
list2 <- data.frame(subject=subj_full, verb=factor(verb_full), traincond=factor(train_full), testorder=factor(testorder_full))

covars <- rbind(list1,list2)
```

```{r}
### Specify the parameters for the model: y ~ traincond + testorder + traincond*testorder + (1|subject) + (1|verb)
# 1.Intercept and slopes for (1)training condition, (2)test order, (3) training condition*test order
fixed <- c(0, 0.4, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2)
# 2.Random intercepts for participants and verbs
rand <- list(0.04, 0.04)
# 3.Residual variance
res <- 0.01
```

```{r}
### Create model
model_syn <- makeLmer(y ~ traincond + testorder + traincond*testorder + (1|subject) + (1|verb), fixef=fixed, VarCorr=rand, sigma=res, data = covars)
summary(model_syn)
```

```{r}
### Specify an effect size ##
fixef(model_syn)["traincondmod"] <- 0.2

### Run power analysis for the effect of training condition
sim_output <- powerSim(model_syn, nsim=100, test = fcompare(y ~ traincond))
sim_output
```

```{r}
### Change the number of participants to 100 people
model_ext_subj <- extend(model_syn, within="traincond", n=100)
model_ext_subj
```

```{r}
### Run power analysis again
model_ext_subj <- extend(model_syn, within="traincond+testorder", n=100)
sim_subj <- powerSim(model_ext_subj, nsim=100, test = fcompare(y ~ traincond))
```

```{r}
### Plot the results
p_curve <- powerCurve(model_ext_subj, test=fcompare(y ~ traincond), within="traincond+testorder", breaks=c(10,15,20,25,30,35))
plot(p_curve)
```
